### ISSUE TITLE
Faraday::ConnectionFailed (getaddrinfo: Name or service not known)

### ISSUE THREAD

**Issue by ant-camp** [PromisePay/promisepay-ruby#18]
ruby -2.1.2
rails 4.1.1
PromisePay 0.0.5
Heroku

Response from post request - create user
`Completed 500 Internal Server Error`

`
Response from /request_token
{
  "errors": {
    "token": [
      "already exists"
    ]
  }
}`

Do these issues correlate with each other?

**Comment by brown2rl** [comment]
@ant-camp I found the ['Faraday error class'](https://github.com/lostisland/faraday/blob/master/lib/faraday/error.rb).  It looks like the `initialize(ex, response=nil)` is returning the server response status.  That's why I'm thinking this is possibly the incorrect URL for the API, or the API token/key is not updated in promisepay
